#Theoretical Questions:

#Question 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

#Answer :

NumPy, which stands for Numerical Python, is a key library in Python used for handling large-scale numerical data. It provides powerful tools for working with multi-dimensional arrays and matrices, along with a suite of mathematical functions that make it highly effective for scientific computing and data analysis.


**Purpose of NumPy in Scientific Computing and Data Analysis:**

Efficient Data Management: NumPy is designed to handle large datasets with greater efficiency than native Python lists. It allows for faster access to data and more compact storage, making it ideal for managing complex numerical data, which is essential in scientific applications.

**Multi-dimensional Arrays:**

The core structure of NumPy is the ndarray, which supports n-dimensional arrays of homogeneous data types. These arrays are crucial for handling vectors, matrices, and higher-dimensional data in fields like linear algebra, machine learning, and physics simulations.

**Comprehensive Mathematical Functions:**

NumPy includes a vast array of mathematical operations, from basic element-wise functions to more complex operations such as matrix multiplication, Fourier transforms, and statistical calculations. This makes it highly useful for tasks involving data analysis and numerical computations.

**Integration with Other Tools:**

NumPy is widely compatible with other scientific and data libraries like Pandas, SciPy, and Matplotlib, making it a foundational tool in Python's scientific and data analysis ecosystem.


**Advantages of NumPy:**

**High Performance:** NumPy arrays are implemented in C, making them faster and more efficient than Python lists. Operations on NumPy arrays are often vectorized, meaning they are performed across entire arrays at once, which boosts performance by avoiding loops and repetitive operations.

**Memory Efficiency:** Arrays in NumPy are stored in contiguous memory blocks and are of fixed data types, which reduces memory overhead compared to Python lists. This structure also improves cache performance, further enhancing speed.

**Vectorized Operations and Broadcasting:**

NumPy allows operations to be applied to entire arrays in a single step, a process known as vectorization. This eliminates the need for explicit loops and results in cleaner, faster code. With broadcasting, NumPy can automatically expand arrays with different shapes to enable operations between them without creating copies, which saves memory and time.

**Easy Integration with Low-Level Code:**

NumPy arrays can be easily passed to and from C, C++, or Fortran, which is beneficial for scientific applications where performance is critical, and some functionality is implemented in these lower-level languages.

**Core of a Rich Ecosystem:**

NumPy serves as the backbone for numerous other Python libraries used in data science and machine learning, such as Pandas for data manipulation, SciPy for more advanced scientific computations, and TensorFlow for machine learning. This makes NumPy a foundational part of Python’s scientific computing environment.


**Enhancing Python’s Numerical Capabilities:**

Element-wise Operations: NumPy allows operations such as addition, multiplication, or exponentiation to be applied directly across entire arrays, making the code more concise and the execution faster compared to iterating over lists with loops.


**Complex Data Handling:**
NumPy simplifies operations on matrices, vectors, and multi-dimensional arrays, which are essential for tasks like solving systems of equations or performing statistical analysis.

**Advanced Indexing and Slicing:**
NumPy provides robust options for slicing, masking, and filtering arrays, allowing users to efficiently manipulate data with greater flexibility.


In summary, NumPy significantly enhances Python’s ability to perform numerical operations by offering high-performance arrays and a broad set of mathematical tools. Its speed, memory efficiency, and integration with other libraries make it a critical tool for scientific computing and data analysis in Python.

#Question 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

#Answer :

In NumPy, both np.mean() and np.average() functions are used to calculate the average of an array, but they serve slightly different purposes and offer distinct features. Here's a breakdown of their differences and when to use each:

#np.mean()

**Purpose:**
This function calculates the arithmetic mean of an array along a specified axis.

**Syntax:** numpy.mean(a, axis=None, dtype=None, out=None, keepdims=False)  

**Parameters:**

**a:**The input array containing the data.

**axis:**The axis or axes along which the mean is computed. If set to None, it calculates the mean of the flattened array.

**dtype:** Specifies the data type used in the computation.

**out:** An optional alternative output array for storing the result.

**keepdims:** If True, the output retains the reduced dimensions with size one.

**Return Value:** Returns the mean of the array elements.

**When to Use:** Use np.mean() when you need a simple average across an array, particularly when all elements have equal importance.



#np.average()

**Purpose:** This function computes the weighted average of an array. It can also perform a standard average if no weights are specified.
Syntax: numpy.average(a, axis=None, weights=None, returned=False)

**Parameters:**

**a:** The input array.

**axis:** The axis or axes along which the average is calculated.

**weights:** Optional weights for each element in the array, which must match the shape of a. If not provided, all elements are considered equally weighted.

**returned:** If set to True, it returns a tuple with the average and the total sum of the weights.

**Return Value:** Gives the weighted average of the array elements or the simple average if weights are omitted.

**When to Use:** Opt for np.average() when elements have varying levels of significance, as it allows you to account for these differences in the calculation.


In [2]:
#Example Usage

import numpy as np

# Sample array
data = np.array([1, 2, 3, 4, 5])

# Using np.mean()
mean_result = np.mean(data)  # Result: 3.0

# Using np.average() without weights
average_result = np.average(data)  # Result: 3.0

# Using np.average() with weights
weights = np.array([1, 2, 3, 4, 5])
weighted_average_result = np.average(data, weights=weights)  # Result: 4.0

choose np.mean() for straightforward averaging when all values are treated equally. In contrast, select np.average() when you need to consider different weights for your data points, enabling a more nuanced average calculation.

#Question 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays

#Answer :

In NumPy, arrays can be reversed along different axes using slicing or the numpy.flip function. Let's explore the methods for 1D and 2D arrays with examples.



In [3]:
#Reversing a 1D Array
#To reverse a 1D array, you can use slicing syntax [::-1].

#Example:

import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse the array using slicing
reversed_1d = arr_1d[::-1]
print(reversed_1d)

[5 4 3 2 1]


**Reversing a 2D Array**

For 2D arrays, you can reverse along different dimensions, such as rows (axis 0) or columns (axis 1).

**1. Reverse the Rows (Axis 0)**
To reverse the rows of a 2D array, use slicing [::-1, :] or numpy.flip(arr, axis=0).



In [4]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse rows using slicing
reversed_rows = arr_2d[::-1, :]
print(reversed_rows)

# Reverse rows using numpy.flip
reversed_rows_flip = np.flip(arr_2d, axis=0)
print(reversed_rows_flip)


[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


**2. Reverse the Columns (Axis 1)**

To reverse the columns, apply slicing [:, ::-1] or numpy.flip(arr, axis=1).

In [8]:
import numpy as np

# Create a sample 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse columns using slicing
reversed_columns = arr_2d[:, ::-1]
print("Reversed columns using slicing:")
print(reversed_columns)

# Reverse columns using numpy.flip
reversed_columns_flip = np.flip(arr_2d, axis=1)
print("\nReversed columns using numpy.flip:")
print(reversed_columns_flip)

Reversed columns using slicing:
[[3 2 1]
 [6 5 4]
 [9 8 7]]

Reversed columns using numpy.flip:
[[3 2 1]
 [6 5 4]
 [9 8 7]]


**3. Reverse Both Rows and Columns**

To reverse both rows and columns at the same time, combine slicing [::-1, ::-1] or use numpy.flip without specifying an axis.

In [10]:
import numpy as np

# Example 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse both rows and columns using slicing
reversed_both = arr_2d[::-1, ::-1]
print("Reversed using slicing:\n", reversed_both)

# Reverse both rows and columns using numpy.flip
reversed_both_flip = np.flip(arr_2d)
print("Reversed using np.flip:\n", reversed_both_flip)

Reversed using slicing:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Reversed using np.flip:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


You can use slicing ([::-1]) to reverse arrays along specific axes.
numpy.flip is another convenient way to reverse arrays along specified dimensions.

These methods provide a simple and flexible way to reverse arrays in NumPy, depending on the dimensions and axes you're working with.

#Question 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

#Answer :

To identify the data type of elements in a NumPy array, you can access the dtype attribute. Here’s a simple example:

In [11]:
import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3])

# Determine the data type of the elements
print(array.dtype)

int64


In this case, array.dtype will output int64, indicating that the elements are 64-bit integers.

**Significance of Data Types in Memory Management and Performance**

**Memory Management:**

**Fixed-size Storage:** NumPy arrays allocate memory in contiguous blocks, and the dtype defines how much memory is assigned to each element. For instance, int32 consumes 4 bytes, whereas float64 requires 8 bytes. Selecting an appropriate data type is vital for optimizing memory usage. Using smaller types, such as int8 instead of int64, can significantly decrease memory usage, especially with large datasets.

**Memory Alignment:** NumPy arrays are optimized for high-performance computations, which often rely on memory alignment for quicker data access. Choosing the right data type enhances cache efficiency and reduces memory access, ultimately speeding up computations.

**Performance:**
Vectorized Operations: NumPy supports vectorized operations that are fine-tuned based on data types. Operations on smaller data types (like int8 or float32) can be executed more quickly than those on larger types (float64) because they require less processing power. The choice of dtype significantly influences the execution speed of arithmetic operations, such as matrix multiplications and element-wise additions.

**Precision:** The dtype also affects the precision of calculations involving floating-point numbers. For example, using float32 might introduce rounding errors, while float64 offers greater accuracy at a performance cost. Striking the right balance between precision and performance is crucial in scientific computing.

Making informed choices about data types in NumPy arrays is essential for optimizing memory use and computational efficiency. This consideration is especially important in large-scale numerical and scientific applications.

#Question 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

#Answer :

**Understanding Ndarrays in NumPy**

Ndarrays (n-dimensional arrays) are the core data structure in NumPy, a library designed for numerical computing in Python. These arrays are powerful tools for handling and manipulating large datasets. Here’s a closer look at their main characteristics and how they differ from standard Python lists.

**Key Features of Ndarrays**

**Homogeneous Data:**
All elements within an ndarray are of the same data type, which can be defined when the array is created (such as integers, floats, etc.). This uniformity leads to better performance and memory efficiency.

**Multidimensional:**
Ndarrays can have any number of dimensions, making it easy to represent complex data structures. For example, a one-dimensional array resembles a vector, while a two-dimensional array is akin to a matrix. Higher dimensions can be used for more intricate data representations.

**Shape and Size:**
Each ndarray has a shape attribute that indicates its dimensions (e.g., (3, 4) for a 3x4 array), while the total number of elements is accessible via the size attribute, which is the product of its dimensions.

**Efficient Operations:**
You can perform element-wise operations directly on ndarrays, allowing mathematical operations across the entire array without explicit iteration. This feature significantly enhances performance and simplicity in computations.

**Memory Efficiency:**
Ndarrays utilize contiguous blocks of memory and are more memory-efficient than Python lists, especially for large datasets, as they have a fixed type.

**Built-in Mathematical Functions:**
NumPy offers a comprehensive suite of mathematical functions that can be applied directly to ndarrays, including operations for linear algebra, statistics, and Fourier transforms.
Differences Between Ndarrays and Python Lists

**Data Type Restrictions:**
Python lists can store elements of varying data types (e.g., integers, strings, and objects), while ndarrays must contain elements of a single type.

**Performance:**
For numerical computations, ndarrays generally outperform lists in both speed and memory efficiency, particularly when dealing with large datasets.

**Functionality:**
Ndarrays benefit from an extensive range of NumPy functions specifically designed for numerical computations, which are not available for standard Python lists.

**Dimensionality:**
While Python lists can be nested to create multi-dimensional structures, they do not inherently support multi-dimensionality like ndarrays.

**Syntax and Usage:**
Operations on ndarrays tend to be more concise and intuitive, thanks to built-in support for vectorization and broadcasting, unlike the more verbose syntax often required for lists.

In [12]:

#Example of Using Ndarrays
#Here’s a brief example illustrating how to create and manipulate ndarrays in NumPy:


import numpy as np

# Creating a 1D ndarray
array_1d = np.array([1, 2, 3, 4])
print("1D Array:", array_1d)

# Creating a 2D ndarray
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

# Element-wise addition
array_sum = array_1d + 5
print("Element-wise Addition:", array_sum)

# Shape and Size
print("Shape of 2D Array:", array_2d.shape)
print("Size of 2D Array:", array_2d.size)


1D Array: [1 2 3 4]
2D Array:
 [[1 2 3]
 [4 5 6]]
Element-wise Addition: [6 7 8 9]
Shape of 2D Array: (2, 3)
Size of 2D Array: 6


ndarrays are an essential feature of the NumPy library, providing significant advantages over standard Python lists for numerical data processing. Their performance, functionality, and ease of use make them ideal for scientific and mathematical applications.

#Question 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

#Answer :

NumPy arrays provide substantial advantages compared to Python lists, especially when it comes to handling large-scale numerical tasks. Below are the key performance benefits of using NumPy:

**1. Memory Efficiency**

**Contiguous Storage:** NumPy arrays are allocated in contiguous memory, which enhances access speed due to better cache utilization. This arrangement minimizes cache misses, contributing to improved overall performance.

**Lower Overhead:** Unlike Python lists, which store references to objects and have to manage dynamic resizing, NumPy arrays have a fixed data type and size. This reduces memory overhead, allowing for more efficient storage.

**2. Operational Performance**

**Vectorized Operations:** NumPy supports vectorization, enabling users to perform operations on entire arrays without the need for explicit loops. This leads to more concise and faster code execution.

**Broadcasting Capabilities:** The broadcasting feature allows operations to be performed on arrays of different shapes without requiring explicit resizing, simplifying the code and reducing the need for loops.
**Performance Optimization:** Many of NumPy's operations are implemented in lower-level languages like C or Fortran, which significantly boosts execution speed compared to equivalent Python code that relies on looping through lists.

**3. User-Friendly Features**
Extensive Mathematical Functions: NumPy includes a wide range of optimized mathematical functions for tasks such as linear algebra and statistics. This rich functionality allows for efficient computation that is often more complex to implement using Python lists.

**Multi-dimensional Array Support:** NumPy natively supports multi-dimensional arrays, making it easier to handle complex data structures like matrices and tensors compared to using nested lists.


**4. Enhanced Parallel Processing**

**Optimized for Speed:** NumPy can utilize libraries such as BLAS and LAPACK, which are designed for high-performance computations. This capability allows NumPy to execute operations more efficiently than standard Python lists, which lack such optimizations.

**5. Speed Benefits**

**Faster Computations:** Benchmarks consistently show that NumPy can perform operations on large datasets significantly faster than equivalent operations on Python lists. For instance, tasks like adding two large arrays or calculating their dot product are much quicker with NumPy.

**6. Precision Control Defined Data Types:** NumPy allows users to explicitly specify data types (e.g., float32, int64), which can optimize both memory usage and computation speed based on the specific needs of a task.


**Example of Performance Difference**
To highlight the performance difference, consider the following comparison of array operations using Python lists versus NumPy arrays:


In [13]:
import numpy as np
import time

# Defining the size of the array
size = 10**7

# Timing operations with Python lists
start_time = time.time()
list_a = list(range(size))
list_b = list(range(size))
list_c = [x + y for x, y in zip(list_a, list_b)]
print("List time: ", time.time() - start_time)

# Timing operations with NumPy arrays
start_time = time.time()
array_a = np.arange(size)
array_b = np.arange(size)
array_c = array_a + array_b
print("NumPy time: ", time.time() - start_time)

List time:  2.6124236583709717
NumPy time:  0.11897397041320801


In this example, you will notice that the NumPy operation completes significantly faster than the list comprehension, underscoring the efficiency benefits of using NumPy.


NumPy arrays are purpose-built for numerical computations and provide numerous advantages over Python lists, especially for large-scale operations. Their efficient memory usage, fast execution speeds, and rich functionality make them an essential tool in fields such as data science, machine learning, and scientific research.

#Question 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

#Answer :


In NumPy, the functions vstack() and hstack() are used for stacking arrays in different orientations. Here’s a detailed look at each function along with examples to illustrate their usage and outputs.

**1. vstack()**

**Purpose:** This function stacks arrays vertically (along rows).

**Requirement:** The arrays must have the same shape in all dimensions except for the first one.

In [14]:
#Example:

import numpy as np

# Define two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Stack the arrays vertically
vertical_stack = np.vstack((array1, array2))

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nVertical Stack:")
print(vertical_stack)

Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]

Vertical Stack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


**2. hstack()**

**Purpose:** This function stacks arrays horizontally (along columns).

**Requirement:** The arrays must have the same shape in all dimensions except for the second one.

In [15]:
#Example:

import numpy as np

# Define two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Stack the arrays horizontally
horizontal_stack = np.hstack((array1, array2))

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nHorizontal Stack:")
print(horizontal_stack)

Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]

Horizontal Stack:
[[1 2 5 6]
 [3 4 7 8]]


vstack() combines multiple arrays vertically, adding the rows of each array into a single new array.

hstack() merges arrays horizontally, appending the columns of each array side by side.

Both functions can take multiple arrays at once for stacking.
It is essential to follow the shape requirements; otherwise, a ValueError will occur.

These functions are useful for organizing data into multi-dimensional structures.

#Question 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on variousarray dimensions.

#Answer :

#fliplr()

**Definition:** numpy.fliplr(m) is a function that flips an array horizontally (from left to right).

**Impact on Array Dimensions:**

**1D Arrays:** Flipping has no impact since there's no left or right to flip.

In [16]:
import numpy as np
arr1d = np.array([1, 2, 3])
print(np.fliplr(arr1d.reshape(1, -1)))

[[3 2 1]]


**2D Arrays:**

Each row is mirrored. The rightmost column becomes the leftmost, and so forth.

In [17]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(np.fliplr(arr2d))

[[3 2 1]
 [6 5 4]]


**3D Arrays:**

Each 2D slice along the last axis is flipped horizontally.

In [18]:
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(np.fliplr(arr3d))

[[[3 4]
  [1 2]]

 [[7 8]
  [5 6]]]


#flipud()
**Definition:**
numpy.flipud(m) flips an array vertically (from top to bottom).

**Impact on Array Dimensions:**

**1D Arrays:**
Similar to fliplr(), it has no effect on 1D arrays

In [19]:
arr1d = np.array([1, 2, 3])
print(np.flipud(arr1d.reshape(1, -1)))

[[1 2 3]]


**2D Arrays:**
Each column is reversed, meaning the last row becomes the first, and so on.

In [20]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(np.flipud(arr2d))

[[4 5 6]
 [1 2 3]]


**3D Arrays:**
Each 2D slice along the last axis is flipped vertically.



In [21]:
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(np.flipud(arr3d))

[[[5 6]
  [7 8]]

 [[1 2]
  [3 4]]]


**Key Differences**

**Direction of Flipping:**

fliplr(): Mirrors the array horizontally (left to right).

flipud(): Mirrors the array vertically (top to bottom).

**Effects on Array Dimensions:**
Both methods do not change 1D arrays.

For 2D arrays, fliplr() reverses the order of columns, while flipud() reverses the order of rows.

For 3D arrays, both methods flip each 2D slice along the corresponding axis.

These methods are particularly useful for data manipulation tasks, such as image processing, where flipping images or datasets is a common requirement.



#Question 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

#Answer :

The numpy.array_split() function in NumPy is a useful method for dividing an array into multiple sub-arrays along a specified axis. Here’s an overview of its features and how it manages uneven splits:

**Overview of Functionality**

**Basic Syntax:**
numpy.array_split(ary, indices_or_sections, axis=0)


**ary:**
The array that you wish to split.

**indices_or_sections:**
This can be either an integer or a sequence. If it’s an integer, it indicates the number of equal parts to divide the array into. If it’s a sequence, it specifies the indices at which to split the array.

**axis:**
This defines the axis along which the array will be split (default is 0, corresponding to the first axis).


**Handling Even and Uneven Splits**

**Even Splits:**
If the total number of elements in the array can be evenly divided by the number of sections requested, array_split() will generate the specified number of sub-arrays of equal length.

**Uneven Splits:**
When the array cannot be split evenly (for example, splitting an array of 10 elements into 3 sections), array_split() distributes the elements as evenly as possible.In such cases, some of the sub-arrays will contain one more element than the others.

In [22]:
#For instance:

import numpy as np

arr = np.arange(10)  # Creates an array: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
result = np.array_split(arr, 3)  # Splits into 3 parts
print(result)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


Here, the first sub-array contains 4 elements, while the second has 2, and the third has 4.


**Important Points**


array_split() allows for splitting along any specified axis, providing flexibility in how data is handled.

The function consistently returns a list of sub-arrays, which may differ in size when the split is uneven.

It is particularly beneficial for processing segments of larger datasets, such as during cross-validation in machine learning or for parallel computations.

numpy.array_split() efficiently manages both even and uneven splits, ensuring a balanced distribution of elements, which makes it an essential tool for data manipulation within NumPy.

#Question 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

#Answer :

**Vectorization**

**Definition:**
Vectorization in NumPy is the technique of applying operations to entire arrays rather than individual elements. This approach allows you to perform computations on large datasets simultaneously, eliminating the need for explicit loops.


**Benefits:**

**Performance:** Vectorized operations are generally much faster than looping through elements. NumPy achieves this speed by utilizing optimized C and Fortran libraries, reducing the overhead associated with Python loops.

**Code Clarity:** Utilizing vectorized operations can lead to more concise and readable code, making it easier to understand and maintain.

In [24]:
#Example:
import numpy as np

# Define two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Perform vectorized addition
c = a + b  # Results in array([5, 7, 9])


**Broadcasting**


**Definition:**
Broadcasting is a powerful feature in NumPy that allows you to perform arithmetic operations on arrays of differing shapes without manually replicating data. It automatically expands the dimensions of the smaller array to match the larger one during operations.


**Rules for Broadcasting:**
If the arrays have a different number of dimensions, the shape of the smaller array is padded with ones on the left until both arrays have the same shape.

**Two arrays are compatible for operations if:**
They share the same shape, or One of the arrays has a shape of 1 in any dimension.


**Benefits:**

**Memory Efficiency:** Broadcasting prevents the need to create large intermediate arrays, conserving both memory and processing time.
Ease of Use: This feature simplifies the implementation of operations on arrays of various sizes without manual adjustments or iterations.

In [25]:
#Example:

import numpy as np

# Create a 1D array and a 2D array
a = np.array([1, 2, 3])  # Shape (3,)
b = np.array([[10], [20], [30]])  # Shape (3, 1)

# Use broadcasting to add the arrays
c = a + b  # Produces a (3, 3) array: [[11, 12, 13], [21, 22, 23], [31, 32, 33]]

Vectorization and broadcasting are essential features of NumPy that enhance the efficiency of array operations. They enable clean, high-performance computations, making NumPy a preferred choice for various applications in data analysis, scientific computing, and machine learning.



#Practical Questions

#Question 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

#Answer:

In [ ]:
import numpy as np

# Generate a 3x3 array with random integers from 1 to 100
array = np.random.randint(1, 101, size=(3, 3))
print("Original array:")
print(array)

# Transpose the array to interchange rows and columns
transposed_array = array.T
print("\nTransposed array:")
print(transposed_array)

Original array:
[[38 75 12]
 [19 72 72]
 [38 62 18]]

Transposed array:
[[38 19 38]
 [75 72 62]
 [12 72 18]]


This code will create a 3x3 array filled with random integers between 1 and 100, and then transpose it to swap the rows and columns.



#Question 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

#Answer:

Below code to generate a 1D NumPy array with 10 elements, then reshape it into a 2x5 array and finally into a 5x2 array:

In [ ]:
import numpy as np

# Create a 1D array with 10 elements
array_1d = np.arange(10)

# Reshape the 1D array to a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape the 2x5 array to a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)

print("Original 1D array:")
print(array_1d)
print("\nReshaped to 2x5 array:")
print(array_2x5)
print("\nReshaped to 5x2 array:")
print(array_5x2)

Original 1D array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


#Question 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

#Answer:

In [ ]:
import numpy as np

# Generate a 4x4 array with random float values
random_array = np.random.rand(4, 4)

# Add a border of zeros to create a 6x6 array
bordered_array = np.pad(random_array, pad_width=1, mode='constant', constant_values=0)

print("Original 4x4 array with random float values:\n", random_array)
print("\n6x6 array with a border of zeros:\n", bordered_array)


Original 4x4 array with random float values:
 [[0.30955998 0.11251267 0.73119864 0.94217388]
 [0.685327   0.93397372 0.82576167 0.52653407]
 [0.47208369 0.39565694 0.72491265 0.32143466]
 [0.08444018 0.74538661 0.85813405 0.23104169]]

6x6 array with a border of zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.30955998 0.11251267 0.73119864 0.94217388 0.        ]
 [0.         0.685327   0.93397372 0.82576167 0.52653407 0.        ]
 [0.         0.47208369 0.39565694 0.72491265 0.32143466 0.        ]
 [0.         0.08444018 0.74538661 0.85813405 0.23104169 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


This code snippet uses np.random.rand to generate the random values and np.pad to add the zero border.

#Question 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

#Answer:

In [ ]:
import numpy as np

# Generate an array of integers from 10 to 60 with a step of 5
integer_array = np.arange(10, 65, 5)

print("Array of integers from 10 to 60 with a step of 5:\n", integer_array)

Array of integers from 10 to 60 with a step of 5:
 [10 15 20 25 30 35 40 45 50 55 60]


This code snippet uses np.arange to create the array, starting at 10 and ending before 65, with increments of 5.

#Question 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

#Answer:

In [ ]:
import numpy as np

# Initialize a NumPy array containing strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Perform various case transformations
uppercase_strings = np.char.upper(string_array)      # Convert to uppercase
lowercase_strings = np.char.lower(string_array)      # Convert to lowercase
titlecase_strings = np.char.title(string_array)      # Convert to title case
capitalized_strings = np.char.capitalize(string_array) # Capitalize the first letter of each string

# Print the results
print("Original Array: ", string_array)
print("Uppercase: ", uppercase_strings)
print("Lowercase: ", lowercase_strings)
print("Title Case: ", titlecase_strings)
print("Capitalized: ", capitalized_strings)

Original Array:  ['python' 'numpy' 'pandas']
Uppercase:  ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase:  ['python' 'numpy' 'pandas']
Title Case:  ['Python' 'Numpy' 'Pandas']
Capitalized:  ['Python' 'Numpy' 'Pandas']


Above code demonstrates how to manipulate strings in a NumPy array using different case transformations.

#Question 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

#Answer:

In [ ]:
import numpy as np

# Define a NumPy array with a list of words
words_array = np.array(['hello', 'world', 'numpy', 'array', 'example'])

# Create a new array with spaces added between each character in the words
spaced_words_array = np.array([' '.join(char for char in word) for word in words_array])

print(spaced_words_array)


['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y' 'e x a m p l e']


This code achieves the same result by using a different structure and wording. When executed, the output will still be:

Each word in the array now has spaces between its characters.

#Question 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

#Answer:

In [ ]:
import numpy as np

# Define two 2D arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise operations
addition = np.add(array1, array2)
subtraction = np.subtract(array1, array2)
multiplication = np.multiply(array1, array2)
division = np.divide(array1, array2)

# Display the results
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Element-wise Addition:\n", addition)
print("Element-wise Subtraction:\n", subtraction)
print("Element-wise Multiplication:\n", multiplication)
print("Element-wise Division:\n", division)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Element-wise Addition:
 [[ 8 10 12]
 [14 16 18]]
Element-wise Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Element-wise Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Element-wise Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


#Question 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

#Answer:

In [ ]:
import numpy as np

# Generate a 5x5 identity matrix
identity_matrix = np.eye(5)

# Get the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

print("5x5 Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)

5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


#Question 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

#Answer:

The below code to generate a NumPy array of 100 random integers between 0 and 1000, and then find and display all the prime numbers in this array:

In [ ]:
import numpy as np

# Create an array of 100 random integers between 0 and 1000
random_numbers = np.random.randint(0, 1001, 100)

# Function to determine if a number is prime
def check_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

# Extract prime numbers from the array
primes = [number for number in random_numbers if check_prime(number)]

print("Random numbers:", random_numbers)
print("Prime numbers:", primes)


Random numbers: [900 706 813 130 453 638 310 869 630 821 196 106 349 952 950 575  57 351
 137 509 815 740 952 110 451 560 303 234 526  26 382 533 900 510  98  11
 771  84 741 692  79 309 613 172 128 435 958 583 314 717 550 806 164 676
  72 411 233 970 336 351 834 702 373 530 200 415   3 586 659 518 409 759
 896 355   3 787 710 482 723 721 393 666 440 371 310 550 265  54 498 917
 623 273 323 251 956 948 154 484 688 708]
Prime numbers: [821, 349, 137, 509, 11, 79, 613, 233, 373, 3, 659, 409, 3, 787, 251]


This code snippet generates an array of random integers and identifies the prime numbers within it.

#Question 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

#Answer:

a NumPy array for daily temperatures over a month and calculate the weekly averages:

In [ ]:
import numpy as np

# Create an array with daily temperatures for 30 days
daily_temperatures = np.random.randint(20, 35, size=30)  # Temperatures between 20°C and 35°C

# Compute weekly averages
weekly_averages = [np.mean(daily_temperatures[i:i+7]) for i in range(0, 30, 7)]

# Print the results
print("Daily Temperatures for the Month:", daily_temperatures)
print("Weekly Averages:", weekly_averages)

Daily Temperatures for the Month: [31 29 22 22 27 33 22 23 31 32 26 26 31 33 29 34 34 22 33 30 24 33 23 34
 33 33 32 32 31 29]
Weekly Averages: [26.571428571428573, 28.857142857142858, 29.428571428571427, 31.428571428571427, 30.0]



Above code generates random temperatures between 20°C and 35°C for 30 days, calculates the average temperature for each week, and prints both the daily temperatures and the weekly averages.